author:
  name: narlock
description: Pomo - a fully customization command-line pomodoro focus timer.
baseurl: ""

# Build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark
  social_links:
  - { platform: github, user_url: "https://github.com/narlock" }
  - { platform: twitter, user_url: "https://twitter.com/narlockdev"}
  - { platform: youtube, user_url: "https://youtube.com/@narlock"}

header_pages:
  - install.markdown
  - features.markdown
  # - tutorial.markdown
  # - documentation.markdown
